version: 2
project_name: btcx

before:
  hooks:
    - go mod tidy

builds:
  - id: btcx
    main: ./cmd/btcx
    binary: btcx
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: btcx
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE*
      - README*
      - config.example.yaml
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

dockers:
  - image_templates:
      - "ghcr.io/ncecere/btcx:{{ .Version }}-amd64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
    goarch: amd64

  - image_templates:
      - "ghcr.io/ncecere/btcx:{{ .Version }}-arm64"
    use: buildx
    dockerfile: Dockerfile
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--label=org.opencontainers.image.title={{ .ProjectName }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/ncecere/btcx:{{ .Version }}"
    image_templates:
      - "ghcr.io/ncecere/btcx:{{ .Version }}-amd64"
      - "ghcr.io/ncecere/btcx:{{ .Version }}-arm64"

  - name_template: "ghcr.io/ncecere/btcx:latest"
    image_templates:
      - "ghcr.io/ncecere/btcx:{{ .Version }}-amd64"
      - "ghcr.io/ncecere/btcx:{{ .Version }}-arm64"

release:
  github:
    owner: ncecere
    name: btcx
  draft: false
  prerelease: auto
  name_template: "{{ .ProjectName }} {{ .Version }}"
